#!/usr/bin/env node

const FB = require('fb');
const userId = 1112292508879017;

FB.options({ version: 'v2.4', appSecret: '' });
FB.setAccessToken('');

FB.api(`${userId}`, 'get', { }, function (res) {
  if(!res || res.error) {
    console.log(!res ? 'error occurred' : res.error);
    return;
  }
  console.log(res);
});
