#!/usr/bin/env node

const request = require('request');
const config = require('config');
const moment = require('moment');

const today = moment("12-30-2016 00:00");
const tomorrow = moment(today).add(1, 'day').add(15, 'minutes');

const getHours = () => {
  let hours = [];

  while (today.isBefore(tomorrow)) {
    today.add(15, 'minutes');
    const hour = "" + today.format("HH:mm");

    hours.push(hour);
  }

  return hours;
}

const deliver = (hour) => {
  request({
    uri: 'https://api.wit.ai/entities/hour?v=20160526',
    qs: { access_token: '' },
    method: 'GET',
    json: {
      value: hour,
      expressions: [hour]
    }
  }, (err, res) => {
    console.log(res.body);
  });
}

const hours = getHours();

for (let i = 0; i < hours.length; ++i) {
  console.log(hours[i]);
}

deliver(hours[3]);
